export interface Reclamo {
  // Generales
  id: null;
  no: number;
  userReg: String;
  userMod: String;
  // Entidad
  instit: String;
  facNo: String;
  nombPres: String;
  codPres: String;
  med: String;
  naf: String;
  aut: String;
  fechAutor: Date;
  nombARS: String;
  autPor: String;
  montRec: Number;
  nombPac: String;
  cedu: String;
  aflNSS: String;
  sex: String;
  fechaNacimiento: Date;
  edad: Number;
  ing: Date;
  egr: Date;
  dir: String;
  dx: String;
  tipServ: String;
  descServ: String;
  tipo: String;
  espec: String;
  exeq: String;
  ceduMed: String;
  telMed: String;
  lote: Number;
}
